services:
  tiltakspenger-pdfgen:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiltakspenger-pdfgen:latest
    ports:
      - "8085:8080"
    volumes:
      - ./templates:/app/templates
      - ./fonts:/app/fonts
      - ./data:/app/data
      - ./resources:/app/resources
    environment:
      DISABLE_PDF_GET: "false"
      DEV_MODE: "true"
      ENABLE_HTML_ENDPOINT: "true"
      JDK_JAVA_OPTIONS: ${JDK_JAVA_OPTIONS}