services:
  service:
    container_name: tiltakspenger-pdfgen
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      DISABLE_PDF_GET: false
      JDK_JAVA_OPTIONS: ""
    volumes:
      - ./templates:/app/templates
      - ./fonts:/app/fonts
      - ./data:/app/data
      - ./resources:/app/resources
