apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-pdfgen
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  image: {{ image }}
  port: 8080
# Hvis det trengs en ingress så må den lages så den er ulik for dev og prod
  ingresses:
    - https://tiltakspenger-pdfgen.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad-api
  azure:
    application:
      enabled: false
  liveness:
    path: internal/is_alive
    initialDelay: 5
    timeout: 10
  readiness:
    path: internal/is_ready
    initialDelay: 5
    timeout: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
