apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-pdfgen
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - {{ ingress }}
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-meldekort-api
        - application: tiltakspenger-soknad-api
        - application: tiltakspenger-saksbehandling-api
  azure:
    application:
      enabled: false
  liveness:
    path: internal/is_alive
    initialDelay: 5
    timeout: 10
  readiness:
    path: internal/is_ready
    initialDelay: 5
    timeout: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{ replicas }}
    max: {{ replicas }}
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki