name: Build docker image

on:
  workflow_call:
    outputs:
      IMAGE:
        description: "Docker image"
        value: ${{ jobs.build.outputs.IMAGE }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      IMAGE: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: tpts
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
