name: Build, push, and deploy

on: push

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  PRINT_PAYLOAD: true

jobs:
  build:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and push
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev:
    name: Deploy to NAIS dev
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{ env.IMAGE }},name=${{ github.event.repository.name }}

  deploy-prod:
    name: Deploy to NAIS prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yml
          VAR: image=${{ env.IMAGE }},name=${{ github.event.repository.name }}
