name: Build, push and deploy to dev (manual)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build docker image
    uses: ./.github/workflows/.build-image.yml
    permissions:
      contents: read
      id-token: write

  deploy:
    name: Deploy to NAIS (dev)
    needs: build
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}
